### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by ulgens** [hahey/django-migration-vis#6]
I was thinking of adding black as code formatter but wanted to ask before creating the PR. @hahey @hartwork does it sound fine?

**Comment by hartwork** [comment]
After comparing Black with other tools, it became apparent that the results of [yapf](https://github.com/google/yapf) are often more readable than Black's and that Black wastes a lot of vertical space without paying back strong enough value. Also, while having projects consistent across the ecosystem is an interesting idea, Black fixes the "wrong problem", because readability is key, not consistency across projects. So if I have a choice, I'd welcome yapf (or something like it), but vote against Black myself.

**Comment by hartwork** [comment]
PS: Same project with…
- black — https://github.com/git-big-picture/git-big-picture/pull/56/files#diff-3267136480d617b4164aec42d20fa40e20e1d656f314c05d2f2a67031729e6cf
- yapf — https://github.com/git-big-picture/git-big-picture/pull/66/files#diff-a82e0228e8066a044a144906a45985c6adeefafe30e34eaa93b758c16ac483c6

**Comment by ulgens** [comment]
> it became apparent that the results of [yapf](https://github.com/google/yapf) are often more readable than Black's and that Black wastes a lot of vertical space without paying back strong enough value.

I think this is highly subjective but I don't see any value in discussing it with the current contributor count and I don't have strong opinions about both tools. If you think yapf is okay with the config you shared, I can apply it.
